name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'archlinux:base-devel' || '' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo pacman --noconfirm -Syu cmake clang lld git gtk4 libadwaita webkitgtk-6.0 xorg-server-xvfb

      - name: Build
        run: cargo build --verbose
