name: Rust Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly

      - name: Build
        run: cargo build --verbose
